name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . -f ./src/WebApi/Dockerfile --tag my-image-name:$(date +%s)
      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: olakara/weather-service
          registry: docker.io
          addLatest: true
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
